//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServersAndHosts.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class backup
    {
        public int id { get; set; }
        public int id_host { get; set; }
        public int id_server { get; set; }
        public int size_kb { get; set; }
        public System.DateTime when_was { get; set; }
    
        public virtual host host { get; set; }
        public virtual server server { get; set; }
    }
}
