//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServersAndHosts.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class component
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public component()
        {
            this.server_component = new HashSet<server_component>();
        }
    
        public int id { get; set; }
        public int id_component_type { get; set; }
        public string name { get; set; }
        public Nullable<int> mhz { get; set; }
        public Nullable<int> memory { get; set; }
        public Nullable<int> cores { get; set; }
    
        public virtual component_type component_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<server_component> server_component { get; set; }
    }
}
