//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServersAndHosts.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ServersAndHostsEntities2 : DbContext
    {
        public ServersAndHostsEntities2()
            : base("name=ServersAndHostsEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<backup> backup { get; set; }
        public virtual DbSet<component> component { get; set; }
        public virtual DbSet<component_type> component_type { get; set; }
        public virtual DbSet<host> host { get; set; }
        public virtual DbSet<server> server { get; set; }
        public virtual DbSet<server_component> server_component { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
