//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServersAndHosts.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class host
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public host()
        {
            this.backup = new HashSet<backup>();
        }
    
        public int id { get; set; }
        public int id_server { get; set; }
        public int ram_mb { get; set; }
        public int cpu_cores { get; set; }
        public int memory_kb_limit { get; set; }
        public int memory_kb_took { get; set; }
        public string hostname { get; set; }
        public string host_addr { get; set; }
        public string comment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<backup> backup { get; set; }
        public virtual server server { get; set; }
    }
}
