//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServersAndHosts.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class server
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public server()
        {
            this.backup = new HashSet<backup>();
            this.host = new HashSet<host>();
            this.server_component = new HashSet<server_component>();
        }
    
        public int id { get; set; }
        public string address { get; set; }
        public string name_in_network { get; set; }
        public int ram_total_mb { get; set; }
        public int ram_free_mb { get; set; }
        public int memory_total_kb { get; set; }
        public int memory_free_kb { get; set; }
        public int cores_total { get; set; }
        public int cores_free { get; set; }
        public int cpu_frequency_mhz { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<backup> backup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<host> host { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<server_component> server_component { get; set; }
    }
}
