//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServersAndHosts.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class server_component
    {
        public int id { get; set; }
        public int id_server { get; set; }
        public int id_component { get; set; }
    
        public virtual component component { get; set; }
        public virtual server server { get; set; }
    }
}
